// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {HoldemTableN} from "../../contracts/zk/HoldemTableN.sol";
import {ChannelTableBase} from "../../contracts/zk/ChannelTableBase.sol";
import {ChannelStateN, SidePot} from "../../contracts/zk/ChannelStateN.sol";
import {IGameRulesN} from "../../contracts/zk/IGameRulesN.sol";
import {MockGameRulesN} from "../../contracts/test/MockGameRulesN.sol";
import {MockX402} from "../../contracts/test/MockX402.sol";
import {IX402Token} from "../../contracts/games/FlipBookX.sol";
import {X402AuthLib} from "./X402AuthLib.sol";

/// @notice Real-money Gate 1 end-to-end: a contested decryption-SHARE demand is answered
/// on-chain with a REAL secp256k1 Chaum–Pedersen share proof, generated by the live
/// off-chain zk-cards-core crypto via `vm.ffi`. No fixtures, no stubs — the deck,
/// the share, and the DLEQ proof all come from the same prover the game uses, bound to the
/// runtime tableId + slot. Proves: (1) a correct share resolves the dispute (so an honest
/// seat is NEVER force-folded for an action it performed), and (2) a forged share / wrong
/// deck reverts. Requires `--ffi` (run via the `ffi` profile).
contract HoldemShareDisputeTest is Test {
    HoldemTableN internal zk;
    MockGameRulesN internal rules;
    MockX402 internal token;
    address internal treasury = address(0x7);

    uint64 internal constant CLOCK = 30;
    uint8 internal constant DEMAND_SHARE = 2;

    uint256 internal constant N = 3;
    uint32 internal constant SLOT = 4;
    uint8 internal constant DEMAND_SEAT = 2;

    function _pk(uint256 i) internal pure returns (uint256) { return 0xA11CE + i * 0x1000 + 1; }

    // secp256k1 generator — an on-curve key for the non-demand seats (start() requires every seat
    // to register; only the demandSeat needs its REAL pubkey, for the DLEQ proof).
    uint256 internal constant GX = 0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798;
    uint256 internal constant GY = 0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8;
    uint64 internal constant VALID_BEFORE = type(uint64).max;

    function setUp() public {
        zk = new HoldemTableN(treasury, address(0)); // factory=0 skips the clone-check
        rules = new MockGameRulesN();
        token = new MockX402();
        for (uint256 i = 0; i < N; i++) {
            token.mint(vm.addr(_pk(i)), 1_000_000 ether);
        }
    }

    // ── x402 deposit-auth helpers ────────────────────────────────────────────

    function _authFor(uint256 pk, address from, uint256 value, bytes32 nonce) internal returns (HoldemTableN.DepositAuth memory) {
        bytes32 digest = X402AuthLib.receiveDigest(token.DOMAIN_SEPARATOR(), from, address(zk), value, VALID_BEFORE, nonce);
        return HoldemTableN.DepositAuth({from: from, validBefore: VALID_BEFORE, salt: bytes32(0), sig: X402AuthLib.sign65(pk, digest)});
    }

    function _create(uint256 pk, address from, uint256 buyIn, address channelKey, uint256[2] memory deckKey)
        internal
        returns (bytes32 tableId)
    {
        bytes32 nonce = zk.createNonce(from, IX402Token(address(token)), IGameRulesN(address(rules)), buyIn, N, 0, 0, CLOCK, channelKey, deckKey, bytes32(0));
        HoldemTableN.DepositAuth memory auth = _authFor(pk, from, buyIn, nonce);
        vm.prank(from);
        tableId = zk.create(IX402Token(address(token)), IGameRulesN(address(rules)), buyIn, N, 0, 0, CLOCK, channelKey, deckKey, auth);
    }

    function _join(uint256 pk, address from, bytes32 tableId, uint256 stake, address channelKey, uint256[2] memory deckKey) internal {
        bytes32 nonce = zk.joinNonce(tableId, from, channelKey, deckKey, bytes32(0));
        HoldemTableN.DepositAuth memory auth = _authFor(pk, from, stake, nonce);
        vm.prank(from);
        zk.join(tableId, channelKey, deckKey, auth);
    }

    // Decoded generator output (real off-chain crypto).
    struct Gen {
        bytes32 commit;
        uint256[2] pk;
        uint256[2] share;
        uint256[5] proof;
        uint256[] deck;
    }

    function _gen(bytes32 tableId) internal returns (Gen memory g) {
        string[] memory cmd = new string[](6);
        cmd[0] = "../../node_modules/.bin/tsx";
        cmd[1] = "../zk-core/scripts/gen-share-dispute.mts";
        cmd[2] = vm.toString(tableId);
        cmd[3] = vm.toString(uint256(SLOT));
        cmd[4] = vm.toString(N);
        cmd[5] = vm.toString(uint256(DEMAND_SEAT));
        bytes memory res = vm.ffi(cmd);
        (g.commit, g.pk, g.share, g.proof, g.deck) =
            abi.decode(res, (bytes32, uint256[2], uint256[2], uint256[5], uint256[]));
    }

    function _coSign(uint256 n, ChannelStateN memory s) internal view returns (bytes[] memory sigs) {
        bytes32 digest = zk.stateDigest(s);
        sigs = new bytes[](n);
        for (uint256 i = 0; i < n; i++) {
            (uint8 v, bytes32 r, bytes32 ss) = vm.sign(_pk(i), digest);
            sigs[i] = abi.encodePacked(r, ss, v);
        }
    }

    /// create + joins (Forming), then start. DEMAND_SEAT's REAL deck pubkey (needed for the DLEQ
    /// proof it must produce) is set directly at join() time; the others get the generator (they
    /// never have to answer a share here). Returns the generated real-crypto bundle.
    function _setupDisputed(uint256 buyIn) internal returns (bytes32 tableId, Gen memory g) {
        address a0 = vm.addr(_pk(0));
        // seat 0 (the creator) is never DEMAND_SEAT (== 2) in this suite, so the generator is fine.
        tableId = _create(_pk(0), a0, buyIn, a0, [GX, GY]);
        // _gen only needs tableId (for the ctx binding), so it can run before the remaining joins.
        g = _gen(tableId);
        for (uint256 i = 1; i < N; i++) {
            address ai = vm.addr(_pk(i));
            if (i == DEMAND_SEAT) _join(_pk(i), ai, tableId, buyIn, ai, g.pk);
            else _join(_pk(i), ai, tableId, buyIn, ai, [GX, GY]);
        }
        vm.prank(a0);
        zk.start(tableId);

        // a conserving mid-hand co-signed state committing the generated deck
        uint256 total = N * buyIn;
        ChannelStateN memory s;
        s.tableId = tableId;
        s.nonce = 1;
        s.balances = new uint256[](N);
        uint256 keep = buyIn / 2;
        for (uint256 i = 0; i < N; i++) s.balances[i] = keep;
        s.pot = total - keep * N;
        s.sidePots = new SidePot[](0);
        s.deckCommitment = g.commit;
        s.phase = 4;
        s.gameStateHash = keccak256("gs");
        bytes[] memory sigs = _coSign(N, s);

        vm.prank(a0);
        zk.openDispute(tableId, s, sigs, "gs", DEMAND_SEAT, DEMAND_SHARE, SLOT);
        assertEq(uint8(zk.status(tableId)), uint8(ChannelTableBase.Status.Disputed), "disputed");
    }

    /// A correct share + DLEQ proof resolves the dispute on-chain → back to Live. The honest
    /// seat keeps its pot equity and can NEVER be force-folded for a share it actually gave.
    function test_correctShareResolvesDispute() public {
        (bytes32 tableId, Gen memory g) = _setupDisputed(4 ether);

        vm.prank(vm.addr(_pk(DEMAND_SEAT)));
        zk.respondWithShare(tableId, g.deck, g.share, g.proof);

        assertEq(uint8(zk.status(tableId)), uint8(ChannelTableBase.Status.Live), "dispute cleared to Live");

        // the clock can no longer strand the honest seat: resolveTimeout now reverts (no dispute)
        vm.roll(block.number + CLOCK + 1);
        vm.expectRevert(ChannelTableBase.BadStatus.selector);
        zk.resolveTimeout(tableId);
    }

    /// A forged share (tampered z) is rejected → dispute stands (staller cannot escape by lying).
    function test_forgedShareReverts() public {
        (bytes32 tableId, Gen memory g) = _setupDisputed(4 ether);
        g.proof[4] ^= 1; // corrupt the response scalar z

        vm.prank(vm.addr(_pk(DEMAND_SEAT)));
        vm.expectRevert(HoldemTableN.BadShareProof.selector);
        zk.respondWithShare(tableId, g.deck, g.share, g.proof);
        assertEq(uint8(zk.status(tableId)), uint8(ChannelTableBase.Status.Disputed), "still disputed");
    }

    /// A share for a different (valid) point fails the DLEQ → rejected.
    function test_wrongSharePointReverts() public {
        (bytes32 tableId, Gen memory g) = _setupDisputed(4 ether);
        // replace the share with another deck point (on-curve, but wrong decryption)
        g.share[0] = g.deck[0];
        g.share[1] = g.deck[1];

        vm.prank(vm.addr(_pk(DEMAND_SEAT)));
        vm.expectRevert(HoldemTableN.BadShareProof.selector);
        zk.respondWithShare(tableId, g.deck, g.share, g.proof);
    }

    /// A deck that does not match the committed deck is rejected before any crypto.
    function test_wrongDeckReverts() public {
        (bytes32 tableId, Gen memory g) = _setupDisputed(4 ether);
        g.deck[0] ^= 1; // break the commitment binding

        vm.prank(vm.addr(_pk(DEMAND_SEAT)));
        vm.expectRevert(ChannelTableBase.BadDeck.selector);
        zk.respondWithShare(tableId, g.deck, g.share, g.proof);
    }

    /// Only the demanded seat may answer a SHARE demand.
    function test_onlyDemandSeatMayAnswer() public {
        (bytes32 tableId, Gen memory g) = _setupDisputed(4 ether);
        vm.prank(vm.addr(_pk(0))); // not the demand seat
        vm.expectRevert(ChannelTableBase.NotYourDispute.selector);
        zk.respondWithShare(tableId, g.deck, g.share, g.proof);
    }
}
