// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {HoldemTableN} from "../../contracts/zk/HoldemTableN.sol";
import {ChannelTableBase} from "../../contracts/zk/ChannelTableBase.sol";
import {ChannelStateN, SidePot as ChannelSidePot} from "../../contracts/zk/ChannelStateN.sol";
import {IGameRulesN} from "../../contracts/zk/IGameRulesN.sol";
import {HoldemRules} from "../../contracts/zk/HoldemRules.sol";
import {MockX402} from "../../contracts/test/MockX402.sol";
import {IX402Token} from "../../contracts/games/FlipBookX.sol";
import {X402AuthLib} from "./X402AuthLib.sol";

/// @notice THE definitive real-crypto proof for HoldemTableN's C2 (DEMAND_SHOWDOWN) on-chain
/// adjudication: a full N-party contested showdown, decoded on-chain from REAL secp256k1
/// ElGamal shares + Chaum-Pedersen DLEQ proofs (generated by the SAME production code the real
/// client uses — the holdem package's `showdownReveal.ts#generateShowdownReveals` /
/// `encodeDeckForShowdown`, via `gen-holdem-showdown.mts` / `vm.ffi`), settles to EXACTLY the
/// same payout vector the off-chain engine (`HoldemRules.settleShowdown`, the same contract the
/// on-chain path itself consults) computes for the identical holes/board. No mocks, no fixtures
/// standing in for the crypto: every share, proof, and deck point here is real.
///
/// Covers (see the task's (a)-(e) checklist):
///   (a) HAPPY CONTESTED SHOWDOWN — every seat posts its full reveal batch, `finalizeShowdownN`
///       pays out exactly the `rules.settleShowdown` oracle's vector, including a genuine SIDE
///       POT (short-stacked seat 0 excluded from it) and a non-zero rake.
///   (b) ANSWER-AWARE TIMEOUT — one seat withholds ONLY its own hole-card shares (still
///       contributing its shares toward the board + the other seats' holes, which the N-party
///       joint-decryption scheme needs from EVERY seat regardless of whose cards are being
///       decoded); `resolveShowdownTimeout` after the clock forfeits that seat's pot
///       eligibility and settles the pot among the answerers — no freeze, no steal, exact
///       conservation.
///   (c) DUPLICATE/BAD DECODE -> SPLIT — a deck with one plaintext card assigned to two required
///       slots (a masking-side deviation, never attributable to either seat's honest, DLEQ-proven
///       reveal) makes the whole-showdown decode "unclean"; `finalizeShowdownN` falls back to the
///       guaranteed-terminal even split, never a steal, conservation exact.
///   (d) C1 — `disputeSetup` -> `resolveTimeout` refunds every seat's exact escrow when a table
///       goes Live with no co-signed state ever pinned.
///   (e) EXHAUSTIVE DISPATCH (H1) — a corrupted/impossible `demandKind` makes `resolveTimeout`
///       revert `BadDemand` rather than silently falling through to the wrong payout rule.
///
/// Requires `--ffi` (runs under the `ffi` profile — see foundry.toml).
contract HoldemTableNShowdownC2Test is Test {
    HoldemTableN internal zk;
    HoldemRules internal rules;
    MockX402 internal token;
    address internal treasury = address(0x7);

    uint64 internal constant CLOCK = 30; // MIN_CLOCK_BLOCKS
    uint8 internal constant SHOWDOWN = 10; // HoldemRules.Phase.SHOWDOWN
    uint8 internal constant DEMAND_SHOWDOWN = 3; // ChannelTableBase.DEMAND_SHOWDOWN
    uint64 internal constant VALID_BEFORE = type(uint64).max;

    function _pk(uint256 i) internal pure returns (uint256) { return 0xA11CE + i * 0x1000 + 1; }
    function _card(uint8 rank, uint8 suit) internal pure returns (uint8) { return (rank - 2) * 4 + suit; }

    function setUp() public {
        zk = new HoldemTableN(treasury, address(0)); // factory=0 skips the x402 wrapper clone-check
        rules = new HoldemRules();
        token = new MockX402();
        for (uint256 i = 0; i <= 9; i++) {
            token.mint(vm.addr(_pk(i)), 10_000_000 ether);
        }
    }

    // ── x402 deposit-auth + table-lifecycle helpers (mirrors HoldemTableNShowdown.t.sol) ───────

    function _authFor(uint256 pk, address from, uint256 value, bytes32 nonce) internal returns (HoldemTableN.DepositAuth memory) {
        bytes32 digest = X402AuthLib.receiveDigest(token.DOMAIN_SEPARATOR(), from, address(zk), value, VALID_BEFORE, nonce);
        return HoldemTableN.DepositAuth({from: from, validBefore: VALID_BEFORE, salt: bytes32(0), sig: X402AuthLib.sign65(pk, digest)});
    }

    function _create(
        uint256 pk,
        uint256 buyIn,
        uint256 maxSeats,
        uint16 rakeBps,
        uint256 rakeCap,
        address channelKey,
        uint256[2] memory deckKey
    ) internal returns (bytes32 tableId) {
        address from = vm.addr(pk);
        bytes32 nonce = zk.createNonce(from, IX402Token(address(token)), IGameRulesN(address(rules)), buyIn, maxSeats, rakeBps, rakeCap, CLOCK, channelKey, deckKey, bytes32(0));
        HoldemTableN.DepositAuth memory auth = _authFor(pk, from, buyIn, nonce);
        vm.prank(from);
        tableId = zk.create(IX402Token(address(token)), IGameRulesN(address(rules)), buyIn, maxSeats, rakeBps, rakeCap, CLOCK, channelKey, deckKey, auth);
    }

    function _join(uint256 pk, bytes32 tableId, uint256 stake, address channelKey, uint256[2] memory deckKey) internal {
        address from = vm.addr(pk);
        bytes32 nonce = zk.joinNonce(tableId, from, channelKey, deckKey, bytes32(0));
        HoldemTableN.DepositAuth memory auth = _authFor(pk, from, stake, nonce);
        vm.prank(from);
        zk.join(tableId, channelKey, deckKey, auth);
    }

    function _pkOf(uint256[] memory pksFlat, uint256 seat) internal pure returns (uint256[2] memory pk) {
        pk[0] = pksFlat[seat * 2];
        pk[1] = pksFlat[seat * 2 + 1];
    }

    /// `n`-seat table, every seat registered with its REAL secp256k1 deck pubkey (from `_genPks`),
    /// joined + started (Live).
    function _setupTable(uint256 n, uint256 buyIn, uint16 rakeBps, uint256 rakeCap, uint256[] memory pksFlat)
        internal
        returns (bytes32 tableId)
    {
        address a0 = vm.addr(_pk(0));
        tableId = _create(_pk(0), buyIn, n, rakeBps, rakeCap, a0, _pkOf(pksFlat, 0));
        for (uint256 i = 1; i < n; i++) {
            address ai = vm.addr(_pk(i));
            _join(_pk(i), tableId, buyIn, ai, _pkOf(pksFlat, i));
        }
        vm.prank(a0);
        zk.start(tableId);
    }

    function _coSign(uint256 n, ChannelStateN memory s) internal view returns (bytes[] memory sigs) {
        bytes32 digest = zk.stateDigest(s);
        sigs = new bytes[](n);
        for (uint256 i = 0; i < n; i++) {
            (uint8 v, bytes32 r, bytes32 ss) = vm.sign(_pk(i), digest);
            sigs[i] = abi.encodePacked(r, ss, v);
        }
    }

    // ── real-crypto generator (vm.ffi -> gen-holdem-showdown.mts) ───────────────────────────────

    /// Cheap: derives the `n` deterministic per-seat deck keypairs (tableId-independent) — used
    /// to register real on-curve deck keys at create()/join(), BEFORE the on-chain tableId exists.
    function _genPks(uint256 n) internal returns (uint256[] memory pksFlat) {
        string[] memory cmd = new string[](4);
        cmd[0] = "../../node_modules/.bin/tsx";
        cmd[1] = "../holdem/scripts/gen-holdem-showdown.mts";
        cmd[2] = "pks";
        cmd[3] = vm.toString(n);
        bytes memory res = vm.ffi(cmd);
        pksFlat = abi.decode(res, (uint256[]));
    }

    /// The real run, AFTER the on-chain tableId is known: masks `cards[slot]` (plaintext card
    /// index 0..51) into each required slot under the joint key, and produces every seat's full
    /// decryption-share + DLEQ-proof batch for all `2n+5` slots, bound to this real tableId.
    function _genFull(bytes32 tableId, uint256 n, uint8[] memory cards)
        internal
        returns (uint256[] memory deck, bytes32 deckCommitment, uint256[] memory sharesFlat, uint256[] memory proofsFlat)
    {
        uint256 numSlots = 2 * n + 5;
        string[] memory cmd = new string[](5 + numSlots);
        cmd[0] = "../../node_modules/.bin/tsx";
        cmd[1] = "../holdem/scripts/gen-holdem-showdown.mts";
        cmd[2] = "full";
        cmd[3] = vm.toString(tableId);
        cmd[4] = vm.toString(n);
        for (uint256 i = 0; i < numSlots; i++) cmd[5 + i] = vm.toString(uint256(cards[i]));
        bytes memory res = vm.ffi(cmd);
        (, deck, deckCommitment, sharesFlat, proofsFlat) =
            abi.decode(res, (uint256[], uint256[], bytes32, uint256[], uint256[]));
    }

    /// deck[slot]=holes[s][0] at s, holes[s][1] at n+s, board[i] at 2n+i — the fixed slot layout
    /// `HoldemShowdownLib._isRequiredSlot` / `requiredShowdownSlots` use for a full live mask.
    function _slotCards(uint256 n, uint8[2][] memory holes, uint8[5] memory board) internal pure returns (uint8[] memory cards) {
        cards = new uint8[](2 * n + 5);
        for (uint256 s = 0; s < n; s++) {
            cards[s] = holes[s][0];
            cards[n + s] = holes[s][1];
        }
        for (uint256 i = 0; i < 5; i++) cards[2 * n + i] = board[i];
    }

    /// Slice one seat's reveal batch out of the generator's flattened (seat-major, slot-minor)
    /// output, skipping any slot in `excludeSlots` — lets a test simulate a seat that withholds
    /// specific slots (e.g. only its own hole cards) rather than its whole reveal.
    function _seatBatch(uint256[] memory sharesFlat, uint256[] memory proofsFlat, uint256 numSlots, uint256 seat, uint256[] memory excludeSlots)
        internal
        pure
        returns (uint32[] memory slots, uint256[2][] memory shares, uint256[5][] memory proofs)
    {
        bool[] memory skip = new bool[](numSlots);
        for (uint256 i = 0; i < excludeSlots.length; i++) skip[excludeSlots[i]] = true;
        uint256 count = 0;
        for (uint256 s = 0; s < numSlots; s++) if (!skip[s]) count++;
        slots = new uint32[](count);
        shares = new uint256[2][](count);
        proofs = new uint256[5][](count);
        uint256 j = 0;
        for (uint256 s = 0; s < numSlots; s++) {
            if (skip[s]) continue;
            slots[j] = uint32(s);
            uint256 base = seat * numSlots + s;
            shares[j][0] = sharesFlat[base * 2];
            shares[j][1] = sharesFlat[base * 2 + 1];
            proofs[j][0] = proofsFlat[base * 5];
            proofs[j][1] = proofsFlat[base * 5 + 1];
            proofs[j][2] = proofsFlat[base * 5 + 2];
            proofs[j][3] = proofsFlat[base * 5 + 3];
            proofs[j][4] = proofsFlat[base * 5 + 4];
            j++;
        }
    }

    // ── Holdem gameState / ChannelStateN construction (direct SHOWDOWN-phase state) ─────────────

    function _holdemState(
        uint256 n,
        uint256[] memory stacks,
        uint256 pot,
        uint256[] memory sidePotAmt,
        uint256[] memory sidePotMask,
        uint16 rakeBps,
        uint256 rakeCap
    ) internal pure returns (HoldemRules.Holdem memory s) {
        s.phase = SHOWDOWN;
        s.nSeats = uint8(n);
        s.button = 0;
        s.toAct = 0xff;
        s.stacks = stacks;
        s.committed = new uint256[](n);
        s.totalContributed = new uint256[](n);
        s.folded = new bool[](n);
        s.allIn = new bool[](n);
        s.actedSinceAggression = new bool[](n);
        s.currentBet = 0;
        s.minRaise = 0;
        s.lastAggressor = 0xff;
        s.pot = pot;
        s.sidePots = new HoldemRules.SidePot[](sidePotAmt.length);
        for (uint256 i = 0; i < sidePotAmt.length; i++) {
            s.sidePots[i] = HoldemRules.SidePot({amount: sidePotAmt[i], eligibleMask: sidePotMask[i]});
        }
        s.smallBlind = 1;
        s.bigBlind = 2;
        s.rakeBps = rakeBps;
        s.rakeCap = rakeCap;
        s.stubWinner = 0xff;
        s.rakeAccrued = 0;
    }

    function _channelState(
        bytes32 tableId,
        uint256[] memory balances,
        uint256 pot,
        uint256[] memory sidePotAmt,
        uint256[] memory sidePotMask,
        bytes32 deckCommitment,
        bytes32 gameStateHash
    ) internal pure returns (ChannelStateN memory cs) {
        cs.tableId = tableId;
        cs.nonce = 1;
        cs.balances = balances;
        cs.pot = pot;
        cs.sidePots = new ChannelSidePot[](sidePotAmt.length);
        for (uint256 i = 0; i < sidePotAmt.length; i++) {
            cs.sidePots[i] = ChannelSidePot({amount: sidePotAmt[i], eligibleMask: sidePotMask[i]});
        }
        cs.rakeAccrued = 0;
        cs.deckCommitment = deckCommitment;
        cs.phase = SHOWDOWN;
        cs.gameStateHash = gameStateHash;
    }

    uint256[] internal EMPTY_U256;

    // ══════════════════════════════════════════════════════════════════════════════════
    // (a) HAPPY CONTESTED SHOWDOWN — matches the off-chain HoldemRules oracle exactly,
    //     including a real side pot and a non-zero rake.
    // ══════════════════════════════════════════════════════════════════════════════════

    function test_happyContestedShowdown_matchesOffchainOracle_sidePotAndRake() public {
        uint256 n = 3;
        uint256 buyIn = 10 ether;
        uint16 rakeBps = 250; // MAX_RAKE_BPS
        uint256 rakeCap = 100 ether; // loose, so the bps math actually bites

        uint256[] memory pksFlat = _genPks(n);
        bytes32 tableId = _setupTable(n, buyIn, rakeBps, rakeCap, pksFlat);

        // Board: A(spade) K(spade) Q(heart) 5(diamond) 2(club).
        uint8[5] memory board =
            [_card(14, 0), _card(13, 0), _card(12, 1), _card(5, 2), _card(2, 3)];
        uint8[2][] memory holes = new uint8[2][](n);
        holes[0] = [_card(14, 1), _card(14, 2)]; // A(heart) A(diamond) -> trip aces (best)
        holes[1] = [_card(13, 1), _card(13, 2)]; // K(heart) K(diamond) -> trip kings
        holes[2] = [_card(12, 2), _card(11, 3)]; // Q(diamond) J(club) -> pair queens (worst)

        // seat0 is the short stack (all-in for less): main pot eligible to all 3, side pot
        // eligible to seats 1+2 only. Leftover stacks + pot + side pot conserve to Sigma escrow.
        uint256[] memory stacks = new uint256[](3);
        stacks[0] = 0;
        stacks[1] = 5 ether;
        stacks[2] = 3 ether;
        uint256 pot = 15 ether;
        uint256[] memory spAmt = new uint256[](1);
        spAmt[0] = 7 ether;
        uint256[] memory spMask = new uint256[](1);
        spMask[0] = (uint256(1) << 1) | (uint256(1) << 2);

        HoldemRules.Holdem memory gs = _holdemState(n, stacks, pot, spAmt, spMask, rakeBps, rakeCap);
        bytes memory gameState = abi.encode(gs);
        bytes32 gameStateHash = keccak256(gameState);

        uint8[] memory cards = _slotCards(n, holes, board);
        (uint256[] memory deck, bytes32 deckCommitment, uint256[] memory sharesFlat, uint256[] memory proofsFlat) =
            _genFull(tableId, n, cards);

        ChannelStateN memory state = _channelState(tableId, stacks, pot, spAmt, spMask, deckCommitment, gameStateHash);
        bytes[] memory sigs = _coSign(n, state);

        vm.prank(address(0xBEEF)); // permissionless open
        zk.openShowdownDispute(tableId, state, sigs, gameState);
        assertEq(uint8(zk.status(tableId)), uint8(ChannelTableBase.Status.Disputed), "showdown dispute opened");

        uint256 numSlots = 2 * n + 5;
        for (uint256 seat = 0; seat < n; seat++) {
            (uint32[] memory slots, uint256[2][] memory shares, uint256[5][] memory proofs) =
                _seatBatch(sharesFlat, proofsFlat, numSlots, seat, EMPTY_U256);
            vm.prank(vm.addr(_pk(seat)));
            zk.postShowdownReveals(tableId, uint8(seat), deck, slots, shares, proofs);
        }

        // THE oracle: the exact same rules contract's real showdown adjudication, called
        // directly against the exact same holes/board/gameState — the "off-chain engine" result
        // the on-chain decode-then-settle path must match byte-for-byte.
        (uint256[] memory oraclePayouts, uint256 oracleRake) = rules.settleShowdown(gameState, holes, board, 0);
        uint256 oracleSum = oracleRake;
        for (uint256 i = 0; i < n; i++) oracleSum += oraclePayouts[i];
        assertEq(oracleSum, n * buyIn, "oracle itself conserves Sigma escrow (sanity)");
        // Hand-derived expectation, independent of the oracle call above: trip aces (seat0) wins
        // the main pot (15 - rake), trip kings (seat1) wins the side pot (7, seat0 excluded),
        // rake (2.5% of the 22-ether contested pots = 0.55 ether) is taken from the main pot
        // first (it is processed before the side pot and is large enough to absorb it whole).
        assertEq(oraclePayouts[0], 1445 * 1e16, "oracle: seat0 (trips aces) wins main pot net of rake");
        assertEq(oraclePayouts[1], 12 ether, "oracle: seat1 (trips kings) wins the side pot");
        assertEq(oraclePayouts[2], 3 ether, "oracle: seat2 (pair queens) keeps only its leftover stack");
        assertEq(oracleRake, 55 * 1e16, "oracle: rake = 2.5% of the 22-ether contested pots");

        uint256[] memory before = new uint256[](n);
        for (uint256 i = 0; i < n; i++) before[i] = token.balanceOf(vm.addr(_pk(i)));
        uint256 treBefore = token.balanceOf(treasury);
        uint256 zkBefore = token.balanceOf(address(zk));

        zk.finalizeShowdownN(tableId, deck, gameState);

        for (uint256 i = 0; i < n; i++) {
            assertEq(token.balanceOf(vm.addr(_pk(i))) - before[i], oraclePayouts[i], "on-chain payout == off-chain oracle payout");
        }
        assertEq(token.balanceOf(treasury) - treBefore, oracleRake, "on-chain rake == off-chain oracle rake");
        assertEq(zkBefore - token.balanceOf(address(zk)), n * buyIn, "exactly Sigma escrow left the contract");
        assertEq(token.balanceOf(address(zk)), 0, "no residue");
        assertEq(uint8(zk.status(tableId)), uint8(ChannelTableBase.Status.Settled), "settled");
    }

    // ══════════════════════════════════════════════════════════════════════════════════
    // (b) ANSWER-AWARE TIMEOUT — a withholding seat forfeits pot eligibility; the table
    //     settles among the answerers. No freeze, no steal, exact conservation.
    // ══════════════════════════════════════════════════════════════════════════════════

    function test_answerAwareTimeout_withholdingSeatForfeits_settlesAmongAnswerers() public {
        uint256 n = 3;
        uint256 buyIn = 9 ether;
        uint16 rakeBps = 0;
        uint256 rakeCap = 0;

        uint256[] memory pksFlat = _genPks(n);
        bytes32 tableId = _setupTable(n, buyIn, rakeBps, rakeCap, pksFlat);

        uint8[5] memory board =
            [_card(14, 0), _card(13, 0), _card(12, 1), _card(5, 2), _card(2, 3)];
        uint8[2][] memory holes = new uint8[2][](n);
        holes[0] = [_card(14, 1), _card(14, 2)]; // trip aces (best)
        holes[1] = [_card(13, 1), _card(13, 2)]; // trip kings
        holes[2] = [_card(12, 2), _card(11, 3)]; // pair queens (worst, and the withholder)

        uint256[] memory stacks = new uint256[](3); // all-in, nothing left behind
        uint256 pot = 27 ether;

        HoldemRules.Holdem memory gs = _holdemState(n, stacks, pot, EMPTY_U256, EMPTY_U256, rakeBps, rakeCap);
        bytes memory gameState = abi.encode(gs);
        bytes32 gameStateHash = keccak256(gameState);

        uint8[] memory cards = _slotCards(n, holes, board);
        (uint256[] memory deck, bytes32 deckCommitment, uint256[] memory sharesFlat, uint256[] memory proofsFlat) =
            _genFull(tableId, n, cards);

        ChannelStateN memory state = _channelState(tableId, stacks, pot, EMPTY_U256, EMPTY_U256, deckCommitment, gameStateHash);
        bytes[] memory sigs = _coSign(n, state);
        zk.openShowdownDispute(tableId, state, sigs, gameState);

        uint256 numSlots = 2 * n + 5;
        // seat0, seat1 post their FULL reveal batch (fully answered).
        for (uint256 seat = 0; seat < 2; seat++) {
            (uint32[] memory slots, uint256[2][] memory shares, uint256[5][] memory proofs) =
                _seatBatch(sharesFlat, proofsFlat, numSlots, seat, EMPTY_U256);
            vm.prank(vm.addr(_pk(seat)));
            zk.postShowdownReveals(tableId, uint8(seat), deck, slots, shares, proofs);
        }
        // seat2 withholds ONLY its own hole slots {2, n+2=5} — it still contributes its share
        // toward the board + the other seats' holes (required from EVERY seat regardless of
        // whose card is being decoded under the N-party joint key), so it never completes its
        // own requiredCount and is never marked "answered".
        uint256[] memory withhold = new uint256[](2);
        withhold[0] = 2;
        withhold[1] = n + 2;
        (uint32[] memory slots2, uint256[2][] memory shares2, uint256[5][] memory proofs2) =
            _seatBatch(sharesFlat, proofsFlat, numSlots, 2, withhold);
        vm.prank(vm.addr(_pk(2)));
        zk.postShowdownReveals(tableId, 2, deck, slots2, shares2, proofs2);

        vm.roll(block.number + CLOCK + 1);

        uint256[] memory before = new uint256[](n);
        for (uint256 i = 0; i < n; i++) before[i] = token.balanceOf(vm.addr(_pk(i)));

        vm.prank(address(0xBEEF)); // permissionless resolve
        zk.resolveShowdownTimeout(tableId, deck, gameState);

        // seat0 (trip aces) wins the WHOLE pot among the answerers; seat1 (trip kings) loses the
        // hand and gets nothing; seat2 forfeits its pot eligibility for withholding but is never
        // charged beyond that (no steal past its already-committed stake, no freeze).
        assertEq(token.balanceOf(vm.addr(_pk(0))) - before[0], 27 ether, "winner among answerers takes the full pot");
        assertEq(token.balanceOf(vm.addr(_pk(1))) - before[1], 0, "losing answerer gets nothing extra");
        assertEq(token.balanceOf(vm.addr(_pk(2))) - before[2], 0, "withholding seat forfeits pot eligibility, no steal");
        assertEq(token.balanceOf(address(zk)), 0, "conservation: no residue");
        assertEq(uint8(zk.status(tableId)), uint8(ChannelTableBase.Status.Settled), "settled, not frozen");
    }

    // ══════════════════════════════════════════════════════════════════════════════════
    // (b+) F2 (2026-08 griefing fix) — a withholding seat's post-expiry front-run attempt
    //      (one more share, purely to re-extend the clock and dodge the answer-aware timeout)
    //      is rejected outright; resolveShowdownTimeout then forfeits it exactly as in (b).
    // ══════════════════════════════════════════════════════════════════════════════════

    function test_postShowdownReveals_frontRunAfterDeadlineReverts_thenAnswererSweepsPot() public {
        uint256 n = 3;
        uint256 buyIn = 9 ether;
        uint16 rakeBps = 0;
        uint256 rakeCap = 0;

        uint256[] memory pksFlat = _genPks(n);
        bytes32 tableId = _setupTable(n, buyIn, rakeBps, rakeCap, pksFlat);

        uint8[5] memory board =
            [_card(14, 0), _card(13, 0), _card(12, 1), _card(5, 2), _card(2, 3)];
        uint8[2][] memory holes = new uint8[2][](n);
        holes[0] = [_card(14, 1), _card(14, 2)]; // trip aces (best)
        holes[1] = [_card(13, 1), _card(13, 2)]; // trip kings
        holes[2] = [_card(12, 2), _card(11, 3)]; // pair queens (worst, and the withholder)

        uint256[] memory stacks = new uint256[](3); // all-in, nothing left behind
        uint256 pot = 27 ether;

        HoldemRules.Holdem memory gs = _holdemState(n, stacks, pot, EMPTY_U256, EMPTY_U256, rakeBps, rakeCap);
        bytes memory gameState = abi.encode(gs);
        bytes32 gameStateHash = keccak256(gameState);

        uint8[] memory cards = _slotCards(n, holes, board);
        (uint256[] memory deck, bytes32 deckCommitment, uint256[] memory sharesFlat, uint256[] memory proofsFlat) =
            _genFull(tableId, n, cards);

        ChannelStateN memory state = _channelState(tableId, stacks, pot, EMPTY_U256, EMPTY_U256, deckCommitment, gameStateHash);
        bytes[] memory sigs = _coSign(n, state);
        zk.openShowdownDispute(tableId, state, sigs, gameState);

        uint256 numSlots = 2 * n + 5;
        // seat0, seat1 fully answer.
        for (uint256 seat = 0; seat < 2; seat++) {
            (uint32[] memory slots, uint256[2][] memory shares, uint256[5][] memory proofs) =
                _seatBatch(sharesFlat, proofsFlat, numSlots, seat, EMPTY_U256);
            vm.prank(vm.addr(_pk(seat)));
            zk.postShowdownReveals(tableId, uint8(seat), deck, slots, shares, proofs);
        }
        // seat2 withholds ONLY its own hole slots {2, n+2=5} — same fixture as the (b) test
        // above — and so never completes / never gets marked answered.
        uint256[] memory withhold = new uint256[](2);
        withhold[0] = 2;
        withhold[1] = n + 2;
        (uint32[] memory slots2, uint256[2][] memory shares2, uint256[5][] memory proofs2) =
            _seatBatch(sharesFlat, proofsFlat, numSlots, 2, withhold);
        vm.prank(vm.addr(_pk(2)));
        zk.postShowdownReveals(tableId, 2, deck, slots2, shares2, proofs2);

        vm.roll(block.number + CLOCK + 1);

        // Front-run attempt: seat2 (the withholder) tries to land ONE more otherwise-valid share
        // (its withheld hole slot 2) purely to push `disputeDeadline` past the current block and
        // dodge the honest permissionless resolve below. Gate 1 rejects it outright — no more
        // posts are live once the window has lapsed, period.
        uint256[] memory justHole = new uint256[](1);
        justHole[0] = 2;
        (uint32[] memory slotsLate, uint256[2][] memory sharesLate, uint256[5][] memory proofsLate) =
            _seatBatch(sharesFlat, proofsFlat, numSlots, 2, _complementOf(justHole, numSlots));
        vm.prank(vm.addr(_pk(2)));
        vm.expectRevert(HoldemTableN.ShowdownWindowExpired.selector);
        zk.postShowdownReveals(tableId, 2, deck, slotsLate, sharesLate, proofsLate);

        uint256[] memory before = new uint256[](n);
        for (uint256 i = 0; i < n; i++) before[i] = token.balanceOf(vm.addr(_pk(i)));

        vm.prank(address(0xBEEF)); // permissionless resolve — front-run closed, table unfreezes
        zk.resolveShowdownTimeout(tableId, deck, gameState);

        assertEq(token.balanceOf(vm.addr(_pk(0))) - before[0], 27 ether, "winner among answerers takes the full pot");
        assertEq(token.balanceOf(vm.addr(_pk(1))) - before[1], 0, "losing answerer gets nothing extra");
        assertEq(token.balanceOf(vm.addr(_pk(2))) - before[2], 0, "withholding seat forfeits pot eligibility, no steal");
        assertEq(token.balanceOf(address(zk)), 0, "conservation: no residue");
        assertEq(uint8(zk.status(tableId)), uint8(ChannelTableBase.Status.Settled), "settled, not frozen");
    }

    /// `_seatBatch`'s `excludeSlots` param names slots to SKIP; this test wants the OPPOSITE (a
    /// batch containing ONLY `keep`) — invert the set once here rather than special-casing
    /// `_seatBatch` itself.
    function _complementOf(uint256[] memory keep, uint256 numSlots) internal pure returns (uint256[] memory excl) {
        bool[] memory keepMask = new bool[](numSlots);
        for (uint256 i = 0; i < keep.length; i++) keepMask[keep[i]] = true;
        uint256 count = 0;
        for (uint256 s = 0; s < numSlots; s++) if (!keepMask[s]) count++;
        excl = new uint256[](count);
        uint256 j = 0;
        for (uint256 s = 0; s < numSlots; s++) if (!keepMask[s]) excl[j++] = s;
    }

    // ══════════════════════════════════════════════════════════════════════════════════
    // (c) DUPLICATE/BAD DECODE -> guaranteed-terminal SPLIT, never a steal.
    // ══════════════════════════════════════════════════════════════════════════════════

    function test_duplicateDecode_fallsBackToEvenSplit_neverSteals() public {
        uint256 n = 2;
        uint256 buyIn = 8 ether;

        uint256[] memory pksFlat = _genPks(n);
        bytes32 tableId = _setupTable(n, buyIn, 0, 0, pksFlat);

        // n=2 slot layout: hole slots seat0=[0,2], seat1=[1,3]; board=[4,5,6,7,8].
        uint8[] memory cards = new uint8[](9);
        cards[0] = _card(14, 1); // seat0 hole0: A(heart)
        cards[1] = _card(13, 1); // seat1 hole0: K(heart)
        cards[2] = _card(14, 2); // seat0 hole1: A(diamond)
        cards[3] = _card(13, 2); // seat1 hole1: K(diamond)
        cards[4] = cards[0];     // board[0] DUPLICATES seat0's hole0 -> unattributable bad decode
        cards[5] = _card(9, 0);
        cards[6] = _card(5, 2);
        cards[7] = _card(2, 3);
        cards[8] = _card(7, 0);

        uint256[] memory stacks = new uint256[](2); // both all-in
        uint256 pot = 16 ether;

        HoldemRules.Holdem memory gs = _holdemState(n, stacks, pot, EMPTY_U256, EMPTY_U256, 0, 0);
        bytes memory gameState = abi.encode(gs);
        bytes32 gameStateHash = keccak256(gameState);

        (uint256[] memory deck, bytes32 deckCommitment, uint256[] memory sharesFlat, uint256[] memory proofsFlat) =
            _genFull(tableId, n, cards);

        ChannelStateN memory state = _channelState(tableId, stacks, pot, EMPTY_U256, EMPTY_U256, deckCommitment, gameStateHash);
        bytes[] memory sigs = _coSign(n, state);
        zk.openShowdownDispute(tableId, state, sigs, gameState);

        uint256 numSlots = 2 * n + 5;
        for (uint256 seat = 0; seat < n; seat++) {
            (uint32[] memory slots, uint256[2][] memory shares, uint256[5][] memory proofs) =
                _seatBatch(sharesFlat, proofsFlat, numSlots, seat, EMPTY_U256);
            vm.prank(vm.addr(_pk(seat)));
            zk.postShowdownReveals(tableId, uint8(seat), deck, slots, shares, proofs);
        }

        uint256[] memory before = new uint256[](n);
        for (uint256 i = 0; i < n; i++) before[i] = token.balanceOf(vm.addr(_pk(i)));

        zk.finalizeShowdownN(tableId, deck, gameState);

        // Every reveal was honest + DLEQ-proven per seat; the duplicate is purely a masking-side
        // deviation and unattributable to either seat -> guaranteed-terminal EVEN split, never a
        // steal by whichever seat's cards "look" better under the corrupted deck.
        assertEq(token.balanceOf(vm.addr(_pk(0))) - before[0], 8 ether, "even split, seat0");
        assertEq(token.balanceOf(vm.addr(_pk(1))) - before[1], 8 ether, "even split, seat1");
        assertEq(token.balanceOf(address(zk)), 0, "conservation: no residue");
        assertEq(uint8(zk.status(tableId)), uint8(ChannelTableBase.Status.Settled), "settled, not frozen");
    }

    // ══════════════════════════════════════════════════════════════════════════════════
    // (d) C1 — disputeSetup -> resolveTimeout refunds exact escrow.
    // ══════════════════════════════════════════════════════════════════════════════════

    function test_disputeSetup_resolveTimeout_refundsEscrow() public {
        uint256 n = 3;
        uint256 buyIn = 6 ether;
        uint256[] memory pksFlat = _genPks(n);
        bytes32 tableId = _setupTable(n, buyIn, 0, 0, pksFlat);

        vm.prank(vm.addr(_pk(1)));
        zk.disputeSetup(tableId);
        assertEq(uint8(zk.status(tableId)), uint8(ChannelTableBase.Status.Disputed), "setup dispute opened");

        vm.roll(block.number + CLOCK + 1);

        uint256[] memory before = new uint256[](n);
        for (uint256 i = 0; i < n; i++) before[i] = token.balanceOf(vm.addr(_pk(i)));

        vm.prank(address(0xBEEF)); // permissionless
        zk.resolveTimeout(tableId);

        for (uint256 i = 0; i < n; i++) {
            assertEq(token.balanceOf(vm.addr(_pk(i))) - before[i], buyIn, "seat refunded its exact buy-in");
        }
        assertEq(token.balanceOf(address(zk)), 0, "no residue");
        assertEq(uint8(zk.status(tableId)), uint8(ChannelTableBase.Status.Settled), "settled");
    }

    // ══════════════════════════════════════════════════════════════════════════════════
    // (e) EXHAUSTIVE DISPATCH (H1) — an impossible demandKind reverts BadDemand.
    // ══════════════════════════════════════════════════════════════════════════════════

    /// Mirrors HoldemTableNShowdownDispute.t.sol's identical probe: `demandKind` can never take
    /// this value through the public API, so this directly corrupts the packed storage slot
    /// (`Table.demandKind`, slot `keccak256(tableId, 2) + 9`, byte offset 9 — `forge inspect
    /// HoldemTableN storage-layout`) to pin the exhaustive dispatch's final `else`.
    function test_resolveTimeout_revertsBadDemand_onImpossibleDemandKind() public {
        uint256 n = 2;
        uint256[] memory pksFlat = _genPks(n);
        bytes32 tableId = _setupTable(n, 2 ether, 0, 0, pksFlat);

        vm.prank(vm.addr(_pk(0)));
        zk.disputeSetup(tableId); // status=Disputed, demandKind=0, a real deadline set

        bytes32 base = keccak256(abi.encode(tableId, uint256(2)));
        bytes32 slot = bytes32(uint256(base) + 9);
        bytes32 word = vm.load(address(zk), slot);
        uint256 w = uint256(word);
        w &= ~(uint256(0xFF) << (9 * 8)); // clear demandKind's byte
        w |= (uint256(99) << (9 * 8)); // an impossible demandKind (not 0/1/2/3)
        vm.store(address(zk), slot, bytes32(w));

        vm.roll(block.number + CLOCK + 1);
        vm.expectRevert(ChannelTableBase.BadDemand.selector);
        zk.resolveTimeout(tableId);
    }
}
