// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {HoldemTableN} from "../../contracts/zk/HoldemTableN.sol";
import {ChannelStateN, SidePot} from "../../contracts/zk/ChannelStateN.sol";
import {IGameRulesN} from "../../contracts/zk/IGameRulesN.sol";
import {MockGameRulesN} from "../../contracts/test/MockGameRulesN.sol";

/// @notice Real-money Gate 1 end-to-end: a contested decryption-SHARE demand is answered
/// on-chain with a REAL secp256k1 Chaum–Pedersen share proof, generated by the live
/// off-chain zk-cards-core crypto via `vm.ffi`. No fixtures, no stubs — the deck,
/// the share, and the DLEQ proof all come from the same prover the game uses, bound to the
/// runtime tableId + slot. Proves: (1) a correct share resolves the dispute (so an honest
/// seat is NEVER force-folded for an action it performed), and (2) a forged share / wrong
/// deck reverts. Requires `--ffi` (run via the `ffi` profile).
contract HoldemShareDisputeTest is Test {
    HoldemTableN internal zk;
    MockGameRulesN internal rules;
    address internal treasury = address(0x7);

    uint64 internal constant CLOCK = 30;
    uint8 internal constant DEMAND_SHARE = 2;

    uint256 internal constant N = 3;
    uint32 internal constant SLOT = 4;
    uint8 internal constant DEMAND_SEAT = 2;

    function _pk(uint256 i) internal pure returns (uint256) { return 0xA11CE + i * 0x1000 + 1; }

    function setUp() public {
        zk = new HoldemTableN(treasury);
        rules = new MockGameRulesN();
    }

    // Decoded generator output (real off-chain crypto).
    struct Gen {
        bytes32 commit;
        uint256[2] pk;
        uint256[2] share;
        uint256[5] proof;
        uint256[] deck;
    }

    function _gen(bytes32 tableId) internal returns (Gen memory g) {
        string[] memory cmd = new string[](6);
        cmd[0] = "../../node_modules/.bin/tsx";
        cmd[1] = "../zk-core/scripts/gen-share-dispute.mts";
        cmd[2] = vm.toString(tableId);
        cmd[3] = vm.toString(uint256(SLOT));
        cmd[4] = vm.toString(N);
        cmd[5] = vm.toString(uint256(DEMAND_SEAT));
        bytes memory res = vm.ffi(cmd);
        (g.commit, g.pk, g.share, g.proof, g.deck) =
            abi.decode(res, (bytes32, uint256[2], uint256[2], uint256[5], uint256[]));
    }

    function _coSign(uint256 n, ChannelStateN memory s) internal view returns (bytes[] memory sigs) {
        bytes32 digest = zk.stateDigest(s);
        sigs = new bytes[](n);
        for (uint256 i = 0; i < n; i++) {
            (uint8 v, bytes32 r, bytes32 ss) = vm.sign(_pk(i), digest);
            sigs[i] = abi.encodePacked(r, ss, v);
        }
    }

    /// create + joins (Forming), register the demandSeat deck key, then start. Returns the
    /// generated real-crypto bundle.
    function _setupDisputed(uint256 buyIn) internal returns (bytes32 tableId, Gen memory g) {
        address a0 = vm.addr(_pk(0));
        vm.deal(a0, buyIn);
        vm.prank(a0);
        tableId = zk.create{value: buyIn}(IGameRulesN(address(rules)), buyIn, N, 0, 0, CLOCK, a0);
        for (uint256 i = 1; i < N; i++) {
            address ai = vm.addr(_pk(i));
            vm.deal(ai, buyIn);
            vm.prank(ai);
            zk.join{value: buyIn}(tableId, ai);
        }
        g = _gen(tableId);
        // the demandSeat registers its real deck pubkey
        vm.prank(vm.addr(_pk(DEMAND_SEAT)));
        zk.registerDeckKey(tableId, g.pk);
        vm.prank(a0);
        zk.start(tableId);

        // a conserving mid-hand co-signed state committing the generated deck
        uint256 total = N * buyIn;
        ChannelStateN memory s;
        s.tableId = tableId;
        s.nonce = 1;
        s.balances = new uint256[](N);
        uint256 keep = buyIn / 2;
        for (uint256 i = 0; i < N; i++) s.balances[i] = keep;
        s.pot = total - keep * N;
        s.sidePots = new SidePot[](0);
        s.deckCommitment = g.commit;
        s.phase = 4;
        s.gameStateHash = keccak256("gs");
        bytes[] memory sigs = _coSign(N, s);

        vm.prank(a0);
        zk.openDispute(tableId, s, sigs, "gs", DEMAND_SEAT, DEMAND_SHARE, SLOT);
        assertEq(uint8(zk.status(tableId)), uint8(HoldemTableN.Status.Disputed), "disputed");
    }

    /// A correct share + DLEQ proof resolves the dispute on-chain → back to Live. The honest
    /// seat keeps its pot equity and can NEVER be force-folded for a share it actually gave.
    function test_correctShareResolvesDispute() public {
        (bytes32 tableId, Gen memory g) = _setupDisputed(4 ether);

        vm.prank(vm.addr(_pk(DEMAND_SEAT)));
        zk.respondWithShare(tableId, g.deck, g.share, g.proof);

        assertEq(uint8(zk.status(tableId)), uint8(HoldemTableN.Status.Live), "dispute cleared to Live");

        // the clock can no longer strand the honest seat: resolveTimeout now reverts (no dispute)
        vm.roll(block.number + CLOCK + 1);
        vm.expectRevert(HoldemTableN.BadStatus.selector);
        zk.resolveTimeout(tableId);
    }

    /// A forged share (tampered z) is rejected → dispute stands (staller cannot escape by lying).
    function test_forgedShareReverts() public {
        (bytes32 tableId, Gen memory g) = _setupDisputed(4 ether);
        g.proof[4] ^= 1; // corrupt the response scalar z

        vm.prank(vm.addr(_pk(DEMAND_SEAT)));
        vm.expectRevert(HoldemTableN.BadShareProof.selector);
        zk.respondWithShare(tableId, g.deck, g.share, g.proof);
        assertEq(uint8(zk.status(tableId)), uint8(HoldemTableN.Status.Disputed), "still disputed");
    }

    /// A share for a different (valid) point fails the DLEQ → rejected.
    function test_wrongSharePointReverts() public {
        (bytes32 tableId, Gen memory g) = _setupDisputed(4 ether);
        // replace the share with another deck point (on-curve, but wrong decryption)
        g.share[0] = g.deck[0];
        g.share[1] = g.deck[1];

        vm.prank(vm.addr(_pk(DEMAND_SEAT)));
        vm.expectRevert(HoldemTableN.BadShareProof.selector);
        zk.respondWithShare(tableId, g.deck, g.share, g.proof);
    }

    /// A deck that does not match the committed deck is rejected before any crypto.
    function test_wrongDeckReverts() public {
        (bytes32 tableId, Gen memory g) = _setupDisputed(4 ether);
        g.deck[0] ^= 1; // break the commitment binding

        vm.prank(vm.addr(_pk(DEMAND_SEAT)));
        vm.expectRevert(HoldemTableN.BadDeck.selector);
        zk.respondWithShare(tableId, g.deck, g.share, g.proof);
    }

    /// Only the demanded seat may answer a SHARE demand.
    function test_onlyDemandSeatMayAnswer() public {
        (bytes32 tableId, Gen memory g) = _setupDisputed(4 ether);
        vm.prank(vm.addr(_pk(0))); // not the demand seat
        vm.expectRevert(HoldemTableN.NotYourDispute.selector);
        zk.respondWithShare(tableId, g.deck, g.share, g.proof);
    }
}
