import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { Noir } from '@noir-lang/noir_js'
import { Barretenberg, UltraHonkBackend } from '@aztec/bb.js'
import { compileCircuit } from '../src/compile'
import { diceTable } from '../src/paytable'
import { tableSettleInputs, tablePublics, type TableRound } from '../src/tableSettle'

/**
 * Reproducible generator for the GENERIC table-settle ON-CHAIN UltraHonk verifier
 * + a Foundry proof fixture. Mirrors games/zk-settle/scripts/genOnchainVerifier.ts,
 * but emits ONE verifier for the whole pure-RNG family instead of one per game.
 *
 * The witness is a dice@5000 WIN round (parity with the per-game fixture), proving
 * the generic circuit settles the exact same round the dice circuit does.
 *
 * Run: npm run gen:onchain-verifier -w @msgboard/zk-table-settle
 */

const here = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(here, '..')
const repoRoot = resolve(pkgRoot, '../..')

const b32 = (n: bigint) => ('0x' + n.toString(16).padStart(64, '0')) as `0x${string}`
const ROUND: TableRound = {
  serverSeed: b32(1n),
  clientSeed: b32(8n),
  table: diceTable(5000n), // dice@5000: roll 485 < 5000 -> win, mult 198 -> payout 1980
  escrowPlayer: 1000n,
  escrowHouse: 980n, // pot 1980 == payout (escrow ceiling exactly met)
}

async function main() {
  console.log('[gen] compiling tableSettleOnchain circuit...')
  const compiled = await compileCircuit('test-circuits/tableSettleOnchain')

  console.log('[gen] executing witness...')
  const noir = new Noir(compiled.program)
  const inputs = tableSettleInputs(ROUND)
  const { witness } = await noir.execute(inputs)

  const api = await Barretenberg.new({ threads: 1 })
  try {
    const backend = new UltraHonkBackend(compiled.program.bytecode, api)

    console.log('[gen] generating EVM (keccak) UltraHonk proof — first run fetches SRS...')
    const { proof, publicInputs } = await backend.generateProof(witness, { verifierTarget: 'evm' })

    console.log('[gen] verifying proof in-process (sanity gate)...')
    const ok = await backend.verifyProof({ proof, publicInputs }, { verifierTarget: 'evm' })
    if (!ok) throw new Error('generated EVM proof failed in-process verify — aborting')

    console.log('[gen] computing verification key...')
    const vk = await backend.getVerificationKey({ verifierTarget: 'evm' })

    console.log('[gen] exporting Solidity verifier...')
    const solidity = await backend.getSolidityVerifier(vk, { verifierTarget: 'evm' })

    const verifierDir = resolve(repoRoot, 'games/contracts/contracts/zk/generated')
    mkdirSync(verifierDir, { recursive: true })
    const verifierPath = resolve(verifierDir, 'TableSettleHonkVerifier.sol')
    const banner = [
      '// SPDX-License-Identifier: UNLICENSED',
      '// GENERATED FILE — DO NOT EDIT BY HAND.',
      '// Source: games/zk-table-settle/test-circuits/tableSettleOnchain (Noir 1.0.0-beta.20)',
      '// The GENERIC table-settle verifier — ONE verifier for the whole pure-RNG game family.',
      '// Regenerate: npm run gen:onchain-verifier -w @msgboard/zk-table-settle',
      '// bb.js 4.3.1 UltraHonkBackend.getSolidityVerifier (verifierTarget: evm => keccak).',
      '// NOT wired into HouseChannel yet — integration is a later phase.',
      '',
    ].join('\n')
    let body = solidity.replace(/^\s*\/\/ SPDX-License-Identifier:[^\n]*\n/, '')
    body = body.replace(/pragma solidity \^0\.8\.27;/g, 'pragma solidity >=0.8.26;')
    writeFileSync(verifierPath, banner + body)
    console.log(`[gen] wrote ${verifierPath} (${(body.length / 1024).toFixed(1)} KiB source)`)

    const pubs = tablePublics(ROUND)
    const toHex = (u: Uint8Array) => '0x' + Buffer.from(u).toString('hex')
    const fixture = {
      _comment:
        'GENERATED by games/zk-table-settle/scripts/genOnchainVerifier.ts. A real EVM-flavour ' +
        'UltraHonk proof for the GENERIC table circuit settling a dice@5000 WIN (stake 1000, pot 1980, ' +
        'payout 1980). publicInputs are the 197 field elements in circuit pub-param order: rngCommit[32], ' +
        'clientSeedCommit[32], outcomeSpace, segCount, hi[64], mult[64], escrowPlayer, escrowHouse, payoutPlayer.',
      round: {
        serverSeed: ROUND.serverSeed,
        clientSeed: ROUND.clientSeed,
        outcomeSpace: pubs.outcomeSpace.toString(),
        segCount: pubs.segCount.toString(),
        escrowPlayer: pubs.escrowPlayer.toString(),
        escrowHouse: pubs.escrowHouse.toString(),
        payoutPlayer: pubs.payoutPlayer.toString(),
      },
      numPublicInputs: publicInputs.length,
      publicInputs,
      proof: toHex(proof),
    }
    const fixtureDir = resolve(repoRoot, 'games/contracts/test/foundry/fixtures')
    mkdirSync(fixtureDir, { recursive: true })
    const fixturePath = resolve(fixtureDir, 'tableSettleOnchainProof.json')
    writeFileSync(fixturePath, JSON.stringify(fixture, null, 2) + '\n')
    console.log(`[gen] wrote ${fixturePath} (proof ${proof.length} bytes, ${publicInputs.length} public inputs)`)
  } finally {
    await api.destroy()
  }
  console.log('[gen] done.')
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
