/** Fills the README's generated region from openrpc.json and emits the website docs module. */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { renderReference } from '../src/render-reference.js'

const here = dirname(fileURLToPath(import.meta.url))
const clientRoot = join(here, '..')
const repoRoot = join(clientRoot, '..', '..')

const START = '<!-- GENERATED:OPENRPC:START -->'
const END = '<!-- GENERATED:OPENRPC:END -->'

const doc = JSON.parse(readFileSync(join(clientRoot, 'openrpc.json'), 'utf8'))
const reference = renderReference(doc)

// 1) inject the reference into the README between the markers
const readmePath = join(clientRoot, 'README.md')
const readme = readFileSync(readmePath, 'utf8')
const startIdx = readme.indexOf(START)
const endIdx = readme.indexOf(END)
if (startIdx === -1 || endIdx === -1) {
  throw new Error('README is missing the GENERATED:OPENRPC markers')
}
const before = readme.slice(0, startIdx + START.length)
const after = readme.slice(endIdx)
const filledReadme = `${before}\n\n${reference}\n${after}`
writeFileSync(readmePath, filledReadme, 'utf8')

// 2) emit the website docs module (README string + parsed spec) for the on-site portal
const uiLib = join(repoRoot, 'packages', 'ui', 'src', 'lib')
const module = [
  '// GENERATED by packages/sdk/scripts/generate-reference.ts — do not edit by hand.',
  '/* eslint-disable */',
  `export const readme = ${JSON.stringify(filledReadme)}`,
  `export const openrpc = ${JSON.stringify(doc)}`,
  '',
].join('\n')
writeFileSync(join(uiLib, 'docs-content.generated.ts'), module, 'utf8')

console.log('generated README reference region and packages/ui/src/lib/docs-content.generated.ts')
