import * as viem from 'viem'
import { expect } from 'chai'
import hre from 'hardhat'
import { execFileSync } from 'node:child_process'
import { deployZkTableDecoyHarness } from './x402'
import * as expectations from './expectations'

// NOTE ON PROOF PROVENANCE (GPL): the fixture this test consumes is generated by
// games/contracts/scripts/gen-challenge-deck.mts, which uses the GPLv3-derived
// @zypher-game/secret-engine WASM prover — PoC only, pending license review (same posture as
// ZkTableDispute.test.ts / the Foundry ffi suites). The vendored on-chain verifiers
// (ShuffleVerifier52 / uzkge PlonkVerifier) are unchanged; only the off-chain proof GENERATION is
// GPL-derived.
//
// WHY HARDHAT, NOT FOUNDRY: `challengeDeck`'s Wave-2 crypto path needs a REAL `ShuffleVerifier52`
// deployed alongside a REAL `ZkTable`. `ShuffleVerifier52` wraps the vendored uzkge PlonkVerifier,
// which hits solc's Yul "stack too deep" under viaIR:true (see foundry.toml's `zk` profile
// header) — it can ONLY compile with viaIR:false. `ZkTable` itself requires viaIR:true (see
// hardhat.config.ts's per-file override) — it hits the SAME stack-too-deep the other direction.
// Foundry has one solc setting per profile, so no Foundry profile can compile both contracts
// together; Hardhat's PER-FILE compiler overrides (hardhat.config.ts) can and already do (see
// ZkGas.test.ts, which deploys both `ShuffleVerifier52` and `ZkTable` in the same suite). This is
// therefore the ONLY place `challengeDeck` can be exercised against the real verifier end to end;
// the Foundry ffi suite (`ZkTableDecoyUnit.t.sol`) covers the same bookkeeping/dispatch/bond
// logic with a `MockShuffleVerifier52` stand-in instead.
//
// Run: cd games/contracts && npx hardhat test test/ZkTableDecoyChallenge.test.ts
describe('ZkTable.challengeDeck (real Zypher shuffle crypto, deckkey-binding-spec.md Wave-2)', function () {
  this.timeout(180_000) // the WASM prover takes ~30-45s per fixture generation

  type Fixture = {
    deckKeyA: readonly [bigint, bigint]
    deckKeyB: readonly [bigint, bigint]
    aggX: bigint
    aggY: bigint
    pkc: readonly bigint[] // 24 words
    d0: readonly bigint[] // 208 words
    afterDeck1: readonly bigint[] // 208 words
    proof1: viem.Hex
    afterDeck2: readonly bigint[] // 208 words
    proof2: viem.Hex
  }

  const gen = (mode: 'honest' | 'decoy'): Fixture => {
    const out = execFileSync(
      process.execPath,
      ['../../node_modules/.bin/tsx', 'scripts/gen-challenge-deck.mts', mode],
      { cwd: __dirname + '/..', maxBuffer: 1024 * 1024 * 16 },
    )
    const hex = out.toString('utf8').trim() as viem.Hex
    const [deckKeyA, deckKeyB, aggX, aggY, pkc, d0, afterDeck1, proof1, afterDeck2, proof2] = viem.decodeAbiParameters(
      [
        { type: 'uint256[2]' },
        { type: 'uint256[2]' },
        { type: 'uint256' },
        { type: 'uint256' },
        { type: 'uint256[24]' },
        { type: 'uint256[]' },
        { type: 'uint256[]' },
        { type: 'bytes' },
        { type: 'uint256[]' },
        { type: 'bytes' },
      ],
      hex,
    )
    return { deckKeyA, deckKeyB, aggX, aggY, pkc, d0, afterDeck1, proof1, afterDeck2, proof2 } as Fixture
  }

  const stepsFor = (f: Fixture) => {
    const keccakPacked = (words: readonly bigint[]) =>
      viem.keccak256(viem.encodePacked(words.map(() => 'uint256'), words as bigint[]))
    const beforeHash0 = keccakPacked(f.d0)
    const afterHash0 = keccakPacked(f.afterDeck1)
    const afterHash1 = keccakPacked(f.afterDeck2)
    const proofHash0 = viem.keccak256(f.proof1)
    const proofHash1 = viem.keccak256(f.proof2)
    const steps = [
      { authorSeat: 1, beforeHash: beforeHash0, afterHash: afterHash0, proofHash: proofHash0 },
      { authorSeat: 2, beforeHash: afterHash0, afterHash: afterHash1, proofHash: proofHash1 },
    ] as const
    const shuffleRoot = viem.keccak256(
      viem.encodeAbiParameters(
        [{ type: 'tuple[]', components: [
          { name: 'authorSeat', type: 'uint8' },
          { name: 'beforeHash', type: 'bytes32' },
          { name: 'afterHash', type: 'bytes32' },
          { name: 'proofHash', type: 'bytes32' },
        ] }],
        [steps as any],
      ),
    )
    const jointKeyCommit = viem.keccak256(
      viem.encodeAbiParameters(
        [{ type: 'uint256' }, { type: 'uint256' }, { type: 'uint256[24]' }],
        [f.aggX, f.aggY, f.pkc as any],
      ),
    )
    return { steps, shuffleRoot, jointKeyCommit, deckCommitment: afterHash1 }
  }

  const JOIN_STAKE = viem.parseEther('10')
  const BAL_A = viem.parseEther('10')
  const BAL_B = viem.parseEther('10')
  const POT = viem.parseEther('4') + 1n // odd wei
  const CLOCK = 30n

  const setup = async () => {
    // ShuffleVerifier52's vendored VerifierKeyExtra*_52 runtime is ~85KB (over EIP-170) —
    // deploy them normally here (unlike ZkGas.test.ts's etch trick) since hardhat's default
    // network allows unlimited contract size for `hardhat test` runs of this suite; if that
    // ever flips, swap to the same `hardhat_setCode` etch helper ZkGas.test.ts uses.
    const vk1 = await hre.viem.deployContract('VerifierKeyExtra1_52')
    const vk2 = await hre.viem.deployContract('VerifierKeyExtra2_52')
    const verifier = await hre.viem.deployContract('ShuffleVerifier52', [vk1.address, vk2.address])
    const zk = await deployZkTableDecoyHarness(viem.zeroAddress, verifier.address)
    const token = await hre.viem.deployContract('MockX402')
    await token.write.mint([zk.address, viem.parseEther('1000')])
    const [walletA, walletB] = await hre.viem.getWalletClients()
    const a = walletA!.account!.address
    const b = walletB!.account!.address
    return { zk, token, a, b }
  }

  const openDecoyTable = async (
    zk: Awaited<ReturnType<typeof deployZkTableDecoyHarness>>,
    token: viem.Hex,
    a: viem.Hex,
    b: viem.Hex,
    f: Fixture,
    steps: readonly { authorSeat: number; beforeHash: viem.Hex; afterHash: viem.Hex; proofHash: viem.Hex }[],
    shuffleRoot: viem.Hex,
    jointKeyCommit: viem.Hex,
    deckCommitment: viem.Hex,
    tableId: viem.Hex,
  ) => {
    const state = {
      tableId,
      nonce: 1n,
      balanceA: BAL_A,
      balanceB: BAL_B,
      pot: POT,
      deckCommitment,
      phase: 0,
      gameStateHash: viem.zeroHash,
      jointKeyCommit,
      shuffleRoot,
    }
    await zk.write.forceDecoyDispute([tableId, a, b, token, f.deckKeyA, f.deckKeyB, JOIN_STAKE, CLOCK, state])
  }

  it('(a) HONEST transcript: every step verifies -> unattributable, pure pot split (no bond)', async () => {
    const f = gen('honest')
    const { steps, shuffleRoot, jointKeyCommit, deckCommitment } = stepsFor(f)
    const { zk, token, a, b } = await setup()
    const tableId = viem.keccak256(viem.toHex('honest-table'))
    await openDecoyTable(zk, token.address, a, b, f, steps, shuffleRoot, jointKeyCommit, deckCommitment, tableId)

    const afterDecks = [f.afterDeck1, f.afterDeck2] as unknown as readonly (readonly bigint[])[]
    const proofs = [f.proof1, f.proof2] as const
    const beforeA = await token.read.balanceOf([a])
    const beforeB = await token.read.balanceOf([b])

    await zk.write.challengeDeck([tableId, f.pkc as any, steps as any, afterDecks as any, proofs as any])

    const half = POT / 2n
    const expectToA = BAL_A + half + (POT - half * 2n)
    const expectToB = BAL_B + half
    expect((await token.read.balanceOf([a])) - beforeA).to.equal(expectToA)
    expect((await token.read.balanceOf([b])) - beforeB).to.equal(expectToB)
  })

  it('(b) DECOY transcript: seat 2 masks under a wrong key -> attributed, forfeits whole pot', async () => {
    const f = gen('decoy')
    const { steps, shuffleRoot, jointKeyCommit, deckCommitment } = stepsFor(f)
    const { zk, token, a, b } = await setup()
    const tableId = viem.keccak256(viem.toHex('decoy-table'))
    await openDecoyTable(zk, token.address, a, b, f, steps, shuffleRoot, jointKeyCommit, deckCommitment, tableId)

    const afterDecks = [f.afterDeck1, f.afterDeck2] as unknown as readonly (readonly bigint[])[]
    const proofs = [f.proof1, f.proof2] as const
    const beforeA = await token.read.balanceOf([a])
    const beforeB = await token.read.balanceOf([b])

    await zk.write.challengeDeck([tableId, f.pkc as any, steps as any, afterDecks as any, proofs as any])

    expect((await token.read.balanceOf([a])) - beforeA).to.equal(BAL_A + POT, 'honest seat A: balance + WHOLE pot')
    expect((await token.read.balanceOf([b])) - beforeB).to.equal(BAL_B, 'culprit seat B: only its balance')
  })

  it('(c) FRAMING: substituting a foreign proof for an honest step reverts BadTranscript', async () => {
    const f = gen('honest')
    const { steps, shuffleRoot, jointKeyCommit, deckCommitment } = stepsFor(f)
    const { zk, token, a, b } = await setup()
    const tableId = viem.keccak256(viem.toHex('framing-table'))
    await openDecoyTable(zk, token.address, a, b, f, steps, shuffleRoot, jointKeyCommit, deckCommitment, tableId)

    const afterDecks = [f.afterDeck1, f.afterDeck2] as unknown as readonly (readonly bigint[])[]
    const proofs = [f.proof2, f.proof2] as const // proof2 substituted for step 0's slot

    await expectations.revertedWithCustomError(
      zk,
      zk.write.challengeDeck([tableId, f.pkc as any, steps as any, afterDecks as any, proofs as any]),
      'BadTranscript',
    )
  })

  it('(d) POISONED-D0: a transcript claiming a non-canonical head reverts BadTranscript', async () => {
    const f = gen('honest')
    const { steps: honestSteps, jointKeyCommit, deckCommitment } = stepsFor(f)
    const steps = honestSteps.map((s) => ({ ...s })) as { authorSeat: number; beforeHash: viem.Hex; afterHash: viem.Hex; proofHash: viem.Hex }[]
    steps[0]!.beforeHash = viem.keccak256(viem.toHex('not-the-canonical-D0'))
    const shuffleRoot = viem.keccak256(
      viem.encodeAbiParameters(
        [{ type: 'tuple[]', components: [
          { name: 'authorSeat', type: 'uint8' },
          { name: 'beforeHash', type: 'bytes32' },
          { name: 'afterHash', type: 'bytes32' },
          { name: 'proofHash', type: 'bytes32' },
        ] }],
        [steps as any],
      ),
    )
    const { zk, token, a, b } = await setup()
    const tableId = viem.keccak256(viem.toHex('poisoned-table'))
    await openDecoyTable(zk, token.address, a, b, f, steps as any, shuffleRoot, jointKeyCommit, deckCommitment, tableId)

    const afterDecks = [f.afterDeck1, f.afterDeck2] as unknown as readonly (readonly bigint[])[]
    const proofs = [f.proof1, f.proof2] as const

    await expectations.revertedWithCustomError(
      zk,
      zk.write.challengeDeck([tableId, f.pkc as any, steps as any, afterDecks as any, proofs as any]),
      'BadTranscript',
    )
  })

  it('(e) gas: challengeDeck (2 real verify52 steps) stays under 6M', async () => {
    const f = gen('honest')
    const { steps, shuffleRoot, jointKeyCommit, deckCommitment } = stepsFor(f)
    const { zk, token, a, b } = await setup()
    const tableId = viem.keccak256(viem.toHex('gas-table'))
    await openDecoyTable(zk, token.address, a, b, f, steps, shuffleRoot, jointKeyCommit, deckCommitment, tableId)

    const afterDecks = [f.afterDeck1, f.afterDeck2] as unknown as readonly (readonly bigint[])[]
    const proofs = [f.proof1, f.proof2] as const
    const hash = await zk.write.challengeDeck([tableId, f.pkc as any, steps as any, afterDecks as any, proofs as any])
    const publicClient = await hre.viem.getPublicClient()
    const receipt = await publicClient.waitForTransactionReceipt({ hash })
    // eslint-disable-next-line no-console
    console.log(`      gas[challengeDeck 2-step] = ${receipt.gasUsed.toString()} (ceiling 6000000)`)
    expect(receipt.gasUsed).to.be.lessThan(6_000_000n)
  })
})
