/**
 * runPlayerCoSign — the plain async function that drives the player side of a split co-sign
 * session (house key is remote, not in the browser). Extracted from useSession so it can be
 * unit-tested without React rendering.
 *
 * Security properties enforced here (see task-6-brief.md):
 *
 *  1. CSPRNG clientSeed: the caller is responsible for passing a cryptographically random
 *     `cfg.clientSeed` per session (generated via generatePrivateKey() or crypto.getRandomValues
 *     in useSession.start()). This function never generates or overrides the seed.
 *
 *  2. Commit-only at open: `buildOpenRequest` emits `clientSeedCommit = keccak256(clientSeed)`,
 *     NOT the raw seed. The seed is only exposed to the house at round time (in the round-request),
 *     AFTER the open co-signature has fixed `terms.rngCommit` — preventing the house from grinding
 *     its tip against a known clientSeed.
 *
 *  3. Refund-floor consistency: `cfg.openBalances` MUST equal the on-chain escrow amounts.
 *     The caller (useSession) asserts `openBalances === { player: terms.escrowPlayer, house: terms.escrowHouse }`
 *     before calling this function. This function does not re-assert it (the escrow is not visible here),
 *     but it DOES verify the player's co-sign-time balances against `cfg.openBalances` (done inside
 *     `runPlayerSide` → `verifyProposedState`).
 */

import { type Hex } from 'viem'
import {
  runPlayerSide,
  type CoSignTransport,
  commitSeed,
} from '@msgboard/games'
import type { SessionConfig } from '@msgboard/games'

/**
 * Canonical dummy seedTip for the player side of a split co-sign session.
 *
 * The player does not have the house's secret seed tip — it never needs it.
 * `runPlayerSide` (via `verifyProposedState`) does NOT read `seedTip`; the only seed the player
 * validates is the revealed `serverSeed`, checked against the `rngCommit` fixed in the OPEN state.
 *
 * Exported so `useSession.ts` can import this single source of truth rather than duplicating it.
 */
export const DUMMY_SEED_TIP = `0x${'00'.repeat(32)}` as Hex

/** The open-request payload the player sends to the house to begin a session. */
export interface OpenRequestPayload {
  kind: 'open-request'
  tableId: Hex
  /**
   * SECURITY: keccak256(clientSeed). The house MUST NOT receive the plaintext clientSeed at
   * open time — doing so would let it grind its seed tip against a known clientSeed to bias the
   * outcome. The seed is revealed only at round time (in the round-request).
   */
  clientSeedCommit: Hex
}

/** Config for runPlayerCoSign — the player's view of a session. */
export type PlayerCoSignConfig<TParams> = Omit<SessionConfig<TParams>, 'house' | 'seedTip'> & {
  /** Marks that the house key is remote (across the transport). */
  houseRemote: true
  /**
   * The player's high-entropy per-session client seed (MUST be generated by the caller using a
   * CSPRNG: `generatePrivateKey()` or `crypto.getRandomValues` — never `Math.random`).
   * This value is committed at open time (only `keccak256(clientSeed)` is sent to the house)
   * and revealed at round time.
   */
  clientSeed: Hex
  /**
   * Optional callback invoked with the open-request payload BEFORE co-signing begins.
   * The caller (useSession) uses this to post the request to the house via the board transport.
   * Tests use it to capture what was sent and assert commit-only semantics.
   */
  onOpenRequest?: (req: OpenRequestPayload) => void | Promise<void>
}

/**
 * Build the open-request the player sends to the house. Contains `clientSeedCommit` (not the raw
 * `clientSeed`) so the house cannot see the plaintext seed before it has committed its own chain.
 */
export function buildOpenRequest(tableId: Hex, clientSeed: Hex): OpenRequestPayload {
  return {
    kind: 'open-request',
    tableId,
    clientSeedCommit: commitSeed(clientSeed), // keccak256(clientSeed)
  }
}

/**
 * Drive the player side of a split co-sign session.
 *
 * 1. Builds and emits the open-request (commit only — seed is kept private).
 * 2. Calls `runPlayerSide` to co-sign OPEN + ROUND envelopes as they arrive over the transport.
 *
 * This function holds only the player key. The house key lives on the house machine. Co-signatures
 * are exchanged via the injected `CoSignTransport`.
 *
 * Throws if `runPlayerSide` rejects (e.g. the house sends a tampered state or wrong clientSeed).
 */
export async function runPlayerCoSign<TParams>(
  cfg: PlayerCoSignConfig<TParams>,
  transport: CoSignTransport,
): Promise<void> {
  // Emit the open-request with ONLY the commit (not the raw seed).
  const req = buildOpenRequest(cfg.tableId, cfg.clientSeed)
  if (cfg.onOpenRequest) await cfg.onOpenRequest(req)

  // Co-sign OPEN and ROUND as they arrive over the transport. The player only signs states it can
  // independently reconstruct (verifyProposedState in runPlayerSide enforces this).
  // Provide a dummy seedTip — the player does not have the house's secret tip and runPlayerSide
  // never reads it (verifyProposedState only validates the revealed serverSeed against rngCommit).
  await runPlayerSide({ ...cfg, seedTip: DUMMY_SEED_TIP }, transport)
}
