// Generator for the wordle_clue + sudoku_solve circuits: exports the on-chain PLONK verifier AND the
// matching proof fixture from ONE zkey, per circuit, in a single pass.
//
// THE RULE THAT KEEPS THIS SAFE: the committed verifier .sol and the committed fixture JSON must
// always come from the SAME zkey. A fixture proved against a zkey that is NOT the one the committed
// verifier was exported from is internally valid (it sanity-verifies in-process against that zkey's
// own vkey) but MISMATCHED with the on-chain verifier bytecode — exactly the corruption this package
// hit once already. So this script does BOTH artifacts together and must be run as a UNIT; never
// regenerate one alone.
//
// Because build/ is gitignored, the zkey is NOT a committed artifact — the committed verifier+fixture
// pair is the only record of a given setup. What reproduces and what does not (both verified):
//   - the VERIFIER is bit-for-bit reproducible: `plonk setup` is deterministic given (r1cs, ptau), so
//     an unchanged circuit + circom + snarkjs + the pinned Hermez ptau re-exports an identical .sol.
//   - the PROOF is NOT: PLONK proving draws random blinding scalars, so every run emits different
//     proof fields. That is the zero-knowledge property working, not a fault. A regenerated fixture
//     therefore shows a 24-field diff and still verifies against the unchanged verifier.
// So: a verifier diff after a no-op regen means something real changed (circuit/toolchain/ptau) and
// must be explained; a proof-only diff is expected noise.
//
// STALE-ARTIFACT TRAP: setupCircuit() is cache-aware — it reuses build/<name>/<name>_plonk.zkey if
// present and will NOT notice that the circuit source changed. After editing a circuit (or bumping
// circom/snarkjs), `rm -rf build/<name>` first, or you will regenerate against the old zkey.
//
// TRUSTED SETUP: PLONK against the real universal Hermez ptau — there is NO per-circuit ceremony to
// run, and no toxic waste (see src/harness.ts).
//
// Run: cd examples/games/zk-skill && npx tsx scripts/genProofFixtures.ts
// (or: pnpm --filter @msgboard/zk-skill gen:proof-fixtures)

import path from 'node:path'
import {
  setupCircuit,
  prove,
  verify,
  proofToCalldata,
  exportSolidityVerifier,
  writeGenerated,
  PACKAGE_ROOT,
  type CircuitSetup,
} from '../src/harness.js'
import { buildWordleWitnessInput, scoreGuess, wordToIndices } from '../src/wordle.js'
import { buildSudokuWitnessInput } from '../src/sudoku.js'

const REPO_ROOT = path.resolve(PACKAGE_ROOT, '../..')
const FIXTURES_DIR = path.join(REPO_ROOT, 'games/contracts/test/foundry/fixtures')
const GENERATED_DIR = path.join(REPO_ROOT, 'games/contracts/contracts/zk/generated')

function generatedHeader(circuit: string): string {
  return `// SPDX-License-Identifier: GPL-3.0
// GENERATED FILE — DO NOT EDIT BY HAND.
// Source: examples/games/zk-skill/circuits/${circuit}.circom (circom -> snarkjs 0.7.6 PLONK).
// Regenerate: cd examples/games/zk-skill && npx tsx scripts/genProofFixtures.ts
// (or: pnpm --filter @msgboard/zk-skill gen:proof-fixtures)
// Trusted setup: PLONK over the universal Hermez powersOfTau28_hez_final_16.ptau. PLONK has NO
// per-circuit setup, so there is no ceremony to re-run when this circuit changes.
`
}

function writeFixture(name: string, fixture: object) {
  writeGenerated(path.join(FIXTURES_DIR, name), JSON.stringify(fixture, null, 2) + '\n')
}

async function genWordleClue(setup: CircuitSetup) {
  // Same fixed vector as test/wordle_clue.test.ts.
  const word = wordToIndices('crane')
  const guess = wordToIndices('eerie')
  const salt = 424242n
  const clue = scoreGuess(word, guess)
  const witnessInput = await buildWordleWitnessInput({ word, salt, guess, clue })
  const { proof, publicSignals } = await prove(setup, witnessInput)
  const ok = await verify(setup, publicSignals, proof)
  if (!ok) throw new Error('genWordleClue: proof failed in-process verify — aborting')
  if (publicSignals.length !== 11) {
    throw new Error(`genWordleClue: expected 11 public signals, got ${publicSignals.length}`)
  }

  writeGenerated(
    path.join(GENERATED_DIR, 'WordleCluePlonkVerifier.sol'),
    exportSolidityVerifier(setup, 'WordleCluePlonkVerifier', generatedHeader('wordle_clue')),
  )
  writeFixture('wordleClueProof.json', {
    _comment:
      'GENERATED by examples/games/zk-skill/scripts/genProofFixtures.ts. A real PLONK proof for ' +
      'the fixed word="crane"/guess="eerie" vector (see test/wordle_clue.test.ts), proved with the ' +
      'SAME build/wordle_clue/wordle_clue_plonk.zkey the committed WordleCluePlonkVerifier.sol was ' +
      'exported from. publicSignals / the packed pub[] order is [commit, guess[0..4], clue[0..4]] ' +
      '(11 signals), matching circuits/wordle_clue.circom `component main {public [commit, guess, ' +
      'clue]}`. `proof` is the 24-field PLONK proof in snarkjs exportSolidityCallData order, as ' +
      'WordleCluePlonkVerifier.verifyProof(uint256[24],uint256[11]) expects.',
    vector: {
      word,
      guess,
      clue,
      salt: witnessInput.salt,
      commit: witnessInput.commit,
    },
    proof: await proofToCalldata(proof, publicSignals),
    pubSignals: publicSignals,
  })
}

async function genSudokuSolve(setup: CircuitSetup) {
  // Same fixed band-rotation vector as test/sudoku_solve.test.ts.
  const SOLUTION: number[] = [
    1, 2, 3, 4, 5, 6, 7, 8, 9,
    4, 5, 6, 7, 8, 9, 1, 2, 3,
    7, 8, 9, 1, 2, 3, 4, 5, 6,
    2, 3, 1, 5, 6, 4, 8, 9, 7,
    5, 6, 4, 8, 9, 7, 2, 3, 1,
    8, 9, 7, 2, 3, 1, 5, 6, 4,
    3, 1, 2, 6, 4, 5, 9, 7, 8,
    6, 4, 5, 9, 7, 8, 3, 1, 2,
    9, 7, 8, 3, 1, 2, 6, 4, 5,
  ]
  const PUZZLE: number[] = SOLUTION.map((v, i) => {
    const r = Math.floor(i / 9)
    const c = i % 9
    return r === 0 || c === 0 ? v : 0
  })
  // Bind the win proof to this player address (as a field element) — see the nullifier note.
  const player = BigInt('0x' + 'ab'.repeat(20)) // 0xabab...ab, a fixed fixture player

  const witnessInput = await buildSudokuWitnessInput({ puzzle: PUZZLE, solution: SOLUTION, player })
  const { proof, publicSignals } = await prove(setup, witnessInput)
  const ok = await verify(setup, publicSignals, proof)
  if (!ok) throw new Error('genSudokuSolve: proof failed in-process verify — aborting')
  if (publicSignals.length !== 4) {
    throw new Error(`genSudokuSolve: expected 4 public signals, got ${publicSignals.length}`)
  }

  writeGenerated(
    path.join(GENERATED_DIR, 'SudokuSolvePlonkVerifier.sol'),
    exportSolidityVerifier(setup, 'SudokuSolvePlonkVerifier', generatedHeader('sudoku_solve')),
  )
  writeFixture('sudokuSolveProof.json', {
    _comment:
      'GENERATED by examples/games/zk-skill/scripts/genProofFixtures.ts. A real PLONK proof for ' +
      'the fixed band-rotation solution/puzzle vector (see test/sudoku_solve.test.ts), proved with ' +
      'the SAME build/sudoku_solve/sudoku_solve_plonk.zkey the committed ' +
      'SudokuSolvePlonkVerifier.sol was exported from. publicSignals / the packed pub[] order is ' +
      '[nullifier, puzzlePacked[0], puzzlePacked[1], player] (4 signals, snarkjs emits the output ' +
      'nullifier first), matching circuits/sudoku_solve.circom `component main {public ' +
      '[puzzlePacked, player]}` with `signal output nullifier`. The 81-cell puzzle is PACKED into ' +
      '2 field elements (4 bits/cell) — see the circuit header for why (a PLONK zkey costs one ' +
      'Lagrange polynomial per public input; 83 signals meant a 960 MB proving key, vs 66 MB ' +
      'packed). `vector.puzzle` is the unpacked 81 cells; SudokuRules.checkSolve takes those and ' +
      'packs on-chain. `proof` is the 24-field PLONK proof in snarkjs exportSolidityCallData ' +
      'order, as SudokuSolvePlonkVerifier.verifyProof(uint256[24],uint256[4]) expects.',
    vector: {
      puzzle: PUZZLE,
      puzzlePacked: witnessInput.puzzlePacked,
      solution: SOLUTION,
      player: witnessInput.player,
      nullifier: publicSignals[0],
    },
    proof: await proofToCalldata(proof, publicSignals),
    pubSignals: publicSignals,
  })
}

async function main() {
  console.log('[gen] wordle_clue: compile + PLONK setup (universal Hermez ptau)...') // eslint-disable-line no-console
  await genWordleClue(setupCircuit('wordle_clue'))

  console.log('[gen] sudoku_solve: compile + PLONK setup (universal Hermez ptau)...') // eslint-disable-line no-console
  await genSudokuSolve(setupCircuit('sudoku_solve'))

  console.log('[gen] done.') // eslint-disable-line no-console
}

// snarkjs leaves its proving worker threads alive, so node never exits on its own — exit explicitly
// rather than hanging after the artifacts are written.
main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e) // eslint-disable-line no-console
    process.exit(1)
  })
