// Generator for the ZK-Wordle SETTLEMENT circuit (wordle_solve): exports the on-chain PLONK verifier
// AND the matching proof fixture from ONE zkey, in a single pass.
//
// THE RULE THAT KEEPS THIS SAFE (same as genProofFixtures.ts): the committed verifier .sol and the
// committed fixture JSON must come from the SAME zkey. This script exports the Solidity verifier from
// build/wordle_solve/wordle_solve_plonk.zkey and then writes the fixture proved against that same
// zkey — so run it as a UNIT after any circuit change; never regenerate one artifact alone. And after
// editing the circuit, `rm -rf build/wordle_solve` first: setupCircuit() reuses an existing zkey and
// will not notice the source changed.
//
// TRUSTED SETUP: PLONK against the real universal Hermez ptau (see src/harness.ts). PLONK has NO
// per-circuit setup, so unlike the old groth16 path there is no ceremony to re-run when this circuit
// changes, and no toxic waste.
//
// Run: cd examples/games/zk-skill && npx tsx scripts/genWordleSolve.ts
// (or: pnpm --filter @msgboard/zk-skill gen:wordle-solve)

import path from 'node:path'
import {
  setupCircuit,
  prove,
  verify,
  proofToCalldata,
  exportSolidityVerifier,
  writeGenerated,
  PACKAGE_ROOT,
} from '../src/harness.js'
import { wordToIndices } from '../src/wordle.js'
import {
  buildDictTree,
  buildWordleSolveWitnessInput,
  WORDLE_VALID_GUESSES,
} from '../src/wordleSolve.js'

const REPO_ROOT = path.resolve(PACKAGE_ROOT, '../..')
const FIXTURES_DIR = path.join(REPO_ROOT, 'games/contracts/test/foundry/fixtures')
const VERIFIER_OUT = path.join(
  REPO_ROOT,
  'games/contracts/contracts/zk/generated/WordleSolvePlonkVerifier.sol',
)

const GENERATED_HEADER = `// SPDX-License-Identifier: GPL-3.0
// GENERATED FILE — DO NOT EDIT BY HAND.
// Source: examples/games/zk-skill/circuits/wordle_solve.circom (circom -> snarkjs 0.7.6 PLONK).
// Regenerate: cd examples/games/zk-skill && npx tsx scripts/genWordleSolve.ts
// (or: pnpm --filter @msgboard/zk-skill gen:wordle-solve)
// Trusted setup: PLONK over the universal Hermez powersOfTau28_hez_final_16.ptau. PLONK has NO
// per-circuit setup, so there is no ceremony to re-run when this circuit changes.
`

async function main() {
  console.log('[gen] wordle_solve: compile + PLONK setup (universal Hermez ptau)...') // eslint-disable-line no-console
  const setup = setupCircuit('wordle_solve')

  // Fixture vector: word="crane"; committed 6-guess sequence solves at guess #2 → guesses-used=2 (3.50×).
  // Built against the REAL production dictionary (full 12,972-word canonical Wordle valid-guess list) at
  // PROD_DICT_DEPTH=14, so the fixture's `dictRoot` IS the exact root a mainnet setWordleDictRoot must
  // commit — the foundry WordleRules/SkillSettle tests then verify against the real committed root.
  const dict = await buildDictTree([...WORDLE_VALID_GUESSES])
  const word = wordToIndices('crane')
  const salt = 424242n
  const guesses = ['slate', 'crane', 'ghost', 'dozen', 'jumbo', 'unfit'].map(wordToIndices)

  const input = await buildWordleSolveWitnessInput({ word, salt, guesses, dict })
  const { proof, publicSignals } = await prove(setup, input)
  const ok = await verify(setup, publicSignals, proof)
  if (!ok) throw new Error('genWordleSolve: proof failed in-process verify — aborting')
  if (publicSignals.length !== 4) {
    throw new Error(`genWordleSolve: expected 4 public signals, got ${publicSignals.length}`)
  }
  if (input.guessesUsed !== '2') throw new Error('genWordleSolve: fixture should solve at guess 2')

  writeGenerated(
    VERIFIER_OUT,
    exportSolidityVerifier(setup, 'WordleSolvePlonkVerifier', GENERATED_HEADER),
  )
  writeGenerated(
    path.join(FIXTURES_DIR, 'wordleSolveProof.json'),
    JSON.stringify(
      {
        _comment:
          'GENERATED by examples/games/zk-skill/scripts/genWordleSolve.ts. A real PLONK proof for ' +
          'the ALL-GREEN solve vector word="crane", committed guesses [slate,crane,ghost,dozen,jumbo,' +
          'unfit] (first all-green at guess #2 → guessesUsed=2 → 3.50x). Proved with the SAME ' +
          'build/wordle_solve/wordle_solve_plonk.zkey the committed WordleSolvePlonkVerifier.sol was ' +
          'exported from. publicSignals / packed pub[] order is [commit, guessesCommit, dictRoot, ' +
          'guessesUsed] (4 signals), matching circuits/wordle_solve.circom `component main`. `proof` ' +
          'is the 24-field PLONK proof in snarkjs exportSolidityCallData order, as ' +
          'WordleSolvePlonkVerifier.verifyProof(uint256[24],uint256[4]) expects.',
        vector: {
          word,
          guesses,
          salt: input.salt,
          commit: input.commit,
          guessesCommit: input.guessesCommit,
          dictRoot: input.dictRoot,
          guessesUsed: input.guessesUsed,
        },
        proof: await proofToCalldata(proof, publicSignals),
        pubSignals: publicSignals,
      },
      null,
      2,
    ) + '\n',
  )
  console.log('[gen] done.') // eslint-disable-line no-console
}

// snarkjs leaves its proving worker threads alive, so node never exits on its own — exit explicitly
// rather than hanging after the artifacts are written.
main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e) // eslint-disable-line no-console
    process.exit(1)
  })
