import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { toHex } from 'viem'
import {
  makeZkArchive,
  verifyProof,
  decodePost,
  encodePost,
  signalHash,
  buildGroup,
  proveMembership,
  randomIdentity,
  type ZkPost,
  type ZkGroup,
} from '../src/zk-msgboard.js'

// These tests verify proofs FOR REAL (snarkjs groth16.verify against the committed
// verification key). The proofs are committed fixtures generated by scripts/build-zk.ts
// from the deterministic DEV setup, so the suite is fully offline and needs no build.
const HERE = dirname(fileURLToPath(import.meta.url))
const zkPath = (...parts: string[]): string => resolve(HERE, '..', 'zk', ...parts)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const loadJson = (path: string): any => JSON.parse(readFileSync(path, 'utf8'))

const vkey = loadJson(zkPath('verification_key.json'))
const group = loadJson(zkPath('fixtures', 'group.json')) as ZkGroup
const memberPost = loadJson(zkPath('fixtures', 'member-post.json')) as ZkPost
const member2Post = loadJson(zkPath('fixtures', 'member2-post.json')) as ZkPost
const outsiderPost = loadJson(zkPath('fixtures', 'outsider-post.json')) as ZkPost

// Deep-clone a fixture so mutations in one test cannot leak into another.
const clone = (post: ZkPost): ZkPost => JSON.parse(JSON.stringify(post)) as ZkPost

describe('verifyProof (real snarkjs groth16 verification)', () => {
  it('accepts a genuine member proof', async () => {
    expect(await verifyProof(vkey, memberPost)).toBe(true)
  })

  it('rejects a proof whose pi_a has been tampered with', async () => {
    const tampered = clone(memberPost)
    tampered.proof.pi_a[0] = tampered.proof.pi_a[0] === '1' ? '2' : '1'
    expect(await verifyProof(vkey, tampered)).toBe(false)
  })

  it('rejects a proof whose public signals have been swapped', async () => {
    const forged = clone(memberPost)
    forged.publicSignals = [...member2Post.publicSignals] // proof no longer matches signals
    expect(await verifyProof(vkey, forged)).toBe(false)
  })
})

describe('makeZkArchive — the zk filter', () => {
  it('admits a valid member and exposes them in the filtered archive', async () => {
    const archive = makeZkArchive({ root: group.root, verificationKey: vkey })
    const result = await archive.offer(memberPost)
    expect(result.accepted).toBe(true)
    expect(archive.size()).toBe(1)
    expect(archive.list()[0].text).toBe('gm from an anonymous member')
  })

  it('admits two DIFFERENT members (distinct nullifiers)', async () => {
    const archive = makeZkArchive({ root: group.root, verificationKey: vkey })
    expect((await archive.offer(memberPost)).accepted).toBe(true)
    expect((await archive.offer(member2Post)).accepted).toBe(true)
    expect(archive.size()).toBe(2)
  })

  it('REJECTS a non-member: a valid proof for a different group (root mismatch)', async () => {
    // Sanity: the outsider proof IS a valid Groth16 proof on its own...
    expect(await verifyProof(vkey, outsiderPost)).toBe(true)
    // ...but it does not belong to the recognized group, so the archive rejects it.
    expect(outsiderPost.publicSignals[0]).not.toBe(group.root)
    const archive = makeZkArchive({ root: group.root, verificationKey: vkey })
    const result = await archive.offer(outsiderPost)
    expect(result.accepted).toBe(false)
    if (!result.accepted) expect(result.reason).toContain('root mismatch')
    expect(archive.size()).toBe(0)
  })

  it('REJECTS a reused nullifier (no double-posting in an epoch)', async () => {
    const archive = makeZkArchive({ root: group.root, verificationKey: vkey })
    expect((await archive.offer(memberPost)).accepted).toBe(true)
    const replay = await archive.offer(memberPost)
    expect(replay.accepted).toBe(false)
    if (!replay.accepted) expect(replay.reason).toContain('nullifier reused')
    expect(archive.size()).toBe(1) // still just the one admission
  })

  it('REJECTS a tampered proof (fails cryptographic verification)', async () => {
    const tampered = clone(memberPost)
    tampered.proof.pi_a[0] = tampered.proof.pi_a[0] === '1' ? '2' : '1'
    const archive = makeZkArchive({ root: group.root, verificationKey: vkey })
    const result = await archive.offer(tampered)
    expect(result.accepted).toBe(false)
    if (!result.accepted) expect(result.reason).toContain('invalid proof')
  })

  it('REJECTS a valid proof lifted onto different content (signal binding)', async () => {
    const lifted: ZkPost = { ...memberPost, payload: toHex('a message I never proved') }
    const archive = makeZkArchive({ root: group.root, verificationKey: vkey })
    const result = await archive.offer(lifted)
    expect(result.accepted).toBe(false)
    if (!result.accepted) expect(result.reason).toContain('signal mismatch')
  })

  it('optionally scopes to an epoch (external nullifier gate)', async () => {
    // Admit under the correct scope, reject under a different one.
    const scoped = makeZkArchive({ root: group.root, verificationKey: vkey, externalNullifier: memberPost.publicSignals[2] })
    expect((await scoped.offer(memberPost)).accepted).toBe(true)

    const wrongEpoch = makeZkArchive({ root: group.root, verificationKey: vkey, externalNullifier: '999' })
    const result = await wrongEpoch.offer(memberPost)
    expect(result.accepted).toBe(false)
    if (!result.accepted) expect(result.reason).toContain('external nullifier mismatch')
  })
})

describe('board wire encoding', () => {
  it('round-trips a post through encode/decode', () => {
    const decoded = decodePost(encodePost(memberPost))
    expect(decoded).not.toBeNull()
    expect(decoded?.publicSignals).toEqual(memberPost.publicSignals)
  })

  it('returns null for non-post data', () => {
    expect(decodePost('0xdeadbeef')).toBeNull()
    expect(decodePost(toHex(JSON.stringify({ hello: 'world' })))).toBeNull()
  })
})

describe('identity + Merkle helpers', () => {
  it('recomputes the committed group root from its member commitments', async () => {
    // Rebuilding the tree from the fixture commitments must reproduce the stored root.
    const leaves = group.commitments.map((c) => BigInt(c))
    const { buildMerkleTree } = await import('../src/zk-msgboard.js')
    const tree = await buildMerkleTree(leaves, group.depth)
    expect(tree.root.toString()).toBe(group.root)
  })

  it('a signal hash is deterministic and inside the field', async () => {
    const h = signalHash(toHex('hello'))
    expect(signalHash(toHex('hello'))).toBe(h)
    expect(h).toBeLessThan(21888242871839275222246405745257275088548364400416034343698204186575808495617n)
  })
})

// This block only runs when the heavy artifacts (wasm + zkey) have been built. It proves
// the FULL post→verify loop end-to-end with a freshly generated proof, not just fixtures.
const WASM = zkPath('build', 'membership_js', 'membership.wasm')
const ZKEY = zkPath('build', 'membership_final.zkey')
const built = existsSync(WASM) && existsSync(ZKEY)

describe.runIf(built)('live proving (requires npm run zk:build)', () => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let freshPost: ZkPost
  let freshRoot: string

  beforeAll(async () => {
    const ids = [randomIdentity(), randomIdentity(), randomIdentity()]
    const { group: g, tree } = await buildGroup(ids)
    freshRoot = g.root
    freshPost = await proveMembership({ identity: ids[2], tree, index: 2, payload: toHex('freshly proven'), scope: 'zkarchive', wasmPath: WASM, zkeyPath: ZKEY })
  }, 60_000)

  it('a freshly generated proof verifies and is admitted', async () => {
    expect(await verifyProof(vkey, freshPost)).toBe(true)
    const archive = makeZkArchive({ root: freshRoot, verificationKey: vkey })
    expect((await archive.offer(freshPost)).accepted).toBe(true)
  })
}, 90_000)
